-- MySQL Script generated by MySQL Workbench
-- Fri Oct  4 02:36:44 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cloud
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cloud` ;

-- -----------------------------------------------------
-- Schema cloud
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cloud` DEFAULT CHARACTER SET utf8 ;
USE `cloud` ;

-- -----------------------------------------------------
-- Table `cloud`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cloud`.`rol` (
  `idrol` INT NOT NULL AUTO_INCREMENT,
  `nombreRol` VARCHAR(45) NULL,
  PRIMARY KEY (`idrol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cloud`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cloud`.`Usuarios` (
  `idUsuarios` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(900) NULL,
  `rol_idrol` INT NOT NULL,
  PRIMARY KEY (`idUsuarios`, `rol_idrol`),
  INDEX `fk_Usuarios_rol_idx` (`rol_idrol` ASC) VISIBLE,
  CONSTRAINT `fk_Usuarios_rol`
    FOREIGN KEY (`rol_idrol`)
    REFERENCES `cloud`.`rol` (`idrol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
